export const LeagerLabel = {
  businessType: "Company Type",
  gstin: "GST No",
  businessName: "Company Name",
  contactPerson: "Contact Person",
  contactNo: "Contact Number",
  email: "Email",
  aadhar: "Aadhar No",
  registrationType: "Registration Type",
  address: "Address",
  city: "City",
  pincode: "PIN Code",
  state: "State",
  country: "Country",
  remaingAmount: "Remaining Amount",
};

export const UnitOfMeasurement = [
  "kg",
  "g",
  "ltr",
  "ml",
  "m",
  "cm",
  "mm",
  "sq.m",
  "sq.ft",
  "ft",
  "in",
  "pcs",
  "box",
  "set",
  "carton",
  "dozen",
  "bag",
];

export const ProductServicesLabel = {
  availableQty: "Stock",
  barcodeOrSerialNo: "Barcode",
  discount: "Discount",
  enable: "Show Product/Service",
  hsnSacCode: "HSN Code",
  itemType: "Item Type",
  name: "Name",
  noItc: "No ITC (Ineligible for Input Tax Credit)",
  nonSalableProduct: "Non-Salable Product",
  normalBatchSerialNo: "Batch Series No",
  productDescription: "Product Description",
  productGroup: "Product Group",
  purchasePrice: "Purchase Price",
  purchasePriceInclTax: "Purchase Price (Including Tax)",
  sellPrice: "Selling Price",
  sellPriceInclTax: "Selling Price (Including Tax)",
  unitOfMeasurement: "Unit of Measurement",
};

export const Payment = {
  companyType: "Company Type",
  companyName: "Company Name",
  billingAddress: "Billing Address",
  gstin: "GSTIN",
  paymentDate: "Payment Date",
  payment: "Pay Amount",
  paymentType: "Payment Type",
  receiptNo: "Receipt No",
};
