export const LableType = {
  companyType: "Company Type",
  gstin: "GST No",
  companyName: "Company Name",
  contactPerson: "Contact Person",
  contactNo: "Contact Number",
  email: "Email",
  registrationType: "Registration Type",
  pan: "PAN",
  billingAddress: "Billing Address",
  address1: "Address 1",
  address2: "Address 2",
  city: "City",
  pincode: "PIN Code",
  state: "State",
  country: "Country",
  distanceForEwayBill: "Distance For E-way Bill",
  balanceType: "Balance Type",
  openingBalance: "Amount",
  licenseNo: "License Number",
  faxNo: "FAX No",
  website: "Website",
  dueDays: "Due Days",
  note: "Note",
  enable: "Enable",
  credit: "Credit",
  registered: "Registered",
  unregistered: "Unregistered",
  customer: "Customer",
  vendor: "Vendor",
  "customer/vendor": "Customer/Vendor",
};
