export const CustomerVendorLabel = {
  companyType: "Company Type",
  gstin: "GST No",
  companyName: "Company Name",
  contactPerson: "Contact Person",
  contactNo: "Contact Number",
  email: "Email",
  registrationType: "Registration Type",
  pan: "PAN",
  billingAddress: "Billing Address",
  address1: "Address 1",
  address2: "Address 2",
  city: "City",
  pincode: "PIN Code",
  state: "State",
  country: "Country",
  distanceForEwayBill: "Distance For E-way Bill",
  balanceType: "Balance Type",
  openingBalance: "Amount",
  licenseNo: "License Number",
  faxNo: "FAX No",
  website: "Website",
  dueDays: "Due Days",
  note: "Note",
  enable: "Enable",
  credit: "Credit",
  registered: "Registered",
  unregistered: "Unregistered",
  customer: "Customer",
  vendor: "Vendor",
  "customer/vendor": "Customer/Vendor",
  remaingAmount: "Remaining Amount",
};

export const UnitOfMeasurement = [
  "kg",
  "g",
  "ltr",
  "ml",
  "m",
  "cm",
  "mm",
  "sq.m",
  "sq.ft",
  "ft",
  "in",
  "pcs",
  "box",
  "set",
  "carton",
  "dozen",
  "bag",
];

export const ProductServicesLabel = {
  availableQty: "Stock",
  barcodeOrSerialNo: "Barcode",
  discount: "Discount",
  enable: "Show Product/Service",
  hsnSacCode: "HSN Code",
  itemType: "Item Type",
  name: "Name",
  noItc: "No ITC (Ineligible for Input Tax Credit)",
  nonSalableProduct: "Non-Salable Product",
  normalBatchSerialNo: "Batch Series No",
  productDescription: "Product Description",
  productGroup: "Product Group",
  purchasePrice: "Purchase Price",
  purchasePriceInclTax: "Purchase Price (Including Tax)",
  sellPrice: "Selling Price",
  sellPriceInclTax: "Selling Price (Including Tax)",
  unitOfMeasurement: "Unit of Measurement",
};
